'use strict';

module.exports = {
  up: queryInterface => queryInterface.bulkInsert('permissoes', [{
    id: 1,
    nome: 'sudo',
    setor_create: true,
    setor_read: true,
    setor_update: true,
    setor_delete: true,
    coord_create: true,
    coord_read: true,
    coord_update: true,
    coord_delete: true,
    meta_create: true,
    meta_read: true,
    meta_update: true,
    meta_delete: true,
    atual_create: true,
    atual_read: true,
    atual_update: true,
    atual_delete: true,
    own_setor_update: true,
    own_setor_delete: true,
    own_coord_update: true,
    own_coord_delete: true,
    own_meta_update: true,
    own_meta_delete: true,
    own_atual_update: true,
    own_atual_delete: true
  }, {
    id: 2,
    nome: 'adm',
    setor_create: false,
    setor_read: true,
    setor_update: false,
    setor_delete: false,
    coord_create: false,
    coord_read: true,
    coord_update: false,
    coord_delete: false,
    meta_create: true,
    meta_read: true,
    meta_update: true,
    meta_delete: true,
    atual_create: true,
    atual_read: true,
    atual_update: true,
    atual_delete: true,
    own_setor_update: true,
    own_setor_delete: false,
    own_coord_update: true,
    own_coord_delete: false,
    own_meta_update: true,
    own_meta_delete: true,
    own_atual_update: true,
    own_atual_delete: true
  }, {
    id: 3,
    nome: 'super',
    setor_create: false,
    setor_read: true,
    setor_update: false,
    setor_delete: false,
    coord_create: false,
    coord_read: true,
    coord_update: false,
    coord_delete: false,
    meta_create: false,
    meta_read: true,
    meta_update: true,
    meta_delete: false,
    atual_create: true,
    atual_read: true,
    atual_update: true,
    atual_delete: false,
    own_setor_update: true,
    own_setor_delete: false,
    own_coord_update: true,
    own_coord_delete: false,
    own_meta_update: true,
    own_meta_delete: false,
    own_atual_update: true,
    own_atual_delete: true
  }, {
    id: 4,
    nome: 'default_user',
    setor_create: false,
    setor_read: true,
    setor_update: false,
    setor_delete: false,
    coord_create: false,
    coord_read: true,
    coord_update: false,
    coord_delete: false,
    meta_create: false,
    meta_read: true,
    meta_update: false,
    meta_delete: false,
    atual_create: true,
    atual_read: true,
    atual_update: false,
    atual_delete: false,
    own_setor_update: false,
    own_setor_delete: false,
    own_coord_update: false,
    own_coord_delete: false,
    own_meta_update: true,
    own_meta_delete: false,
    own_atual_update: false,
    own_atual_delete: false
  }, {
    id: 5,
    nome: 'viewer',
    setor_create: false,
    setor_read: true,
    setor_update: false,
    setor_delete: false,
    coord_create: false,
    coord_read: true,
    coord_update: false,
    coord_delete: false,
    meta_create: false,
    meta_read: true,
    meta_update: false,
    meta_delete: false,
    atual_create: false,
    atual_read: true,
    atual_update: false,
    atual_delete: false,
    own_setor_update: false,
    own_setor_delete: false,
    own_coord_update: false,
    own_coord_delete: false,
    own_meta_update: false,
    own_meta_delete: false,
    own_atual_update: false,
    own_atual_delete: false
  }, {
    id: 6,
    nome: 'any',
    setor_create: false,
    setor_read: false,
    setor_update: false,
    setor_delete: false,
    coord_create: false,
    coord_read: false,
    coord_update: false,
    coord_delete: false,
    meta_create: false,
    meta_read: false,
    meta_update: false,
    meta_delete: false,
    atual_create: false,
    atual_read: false,
    atual_update: false,
    atual_delete: false,
    own_setor_update: false,
    own_setor_delete: false,
    own_coord_update: false,
    own_coord_delete: false,
    own_meta_update: false,
    own_meta_delete: false,
    own_atual_update: false,
    own_atual_delete: false
  }])
  .then(() => queryInterface.bulkInsert('usuarios', [{
    id: 1,
    guid: null,
    matricula: null,
    nome: 'Super User',
    Usuario: 'root',
    senha: '#r001!',
    permissoes: 1,
    setor: null,
    coordenadoria: null
  }]))
  .then(() => queryInterface.bulkInsert('setores', [{
    id: 1,
    nome: 'System Test Department',
    sigla: 'STD',
    endereco: null,
    telefone: null,
    ramal: null,
    autor: 1,
    responsavel: 1
  }]))
  .then(() => queryInterface.bulkInsert('coordenadorias', [{
    id: 1,
    nome: 'Database Test Subdepartment',
    sigla: 'DTS',
    endereco: null,
    telefone: null,
    ramal: null,
    autor: 1,
    responsavel: 1,
    setor: 1
  }]))
  .then(() => queryInterface.bulkInsert('metas', [{
    id: 1,
    titulo: 'Test milestone',
    escopo_previsto: 7.0,
    inicio_previsto: new Date('2018-08-09'),
    fim_previsto: new Date('2018-10-11'),
    custo_previsto: 485.15,
    autor: 1,
    responsavel: 1,
    coordenadoria: 1,
    pai: null
  }]))
  .then(() => queryInterface.bulkInsert('metas', [{
    id: 2,
    titulo: 'Test submilestone',
    escopo_previsto: 7.0,
    inicio_previsto: new Date('2018-08-09'),
    fim_previsto: new Date('2018-10-11'),
    custo_previsto: 485.15,
    autor: 1,
    responsavel: 1,
    coordenadoria: 1,
    pai: 1
  }])),

  down: (queryInterface, s) => queryInterface.bulkDelete('metas', { 'pai': { [s.Op.not]: null } })
  .then(() => queryInterface.bulkDelete('metas'))
  .then(() => queryInterface.bulkDelete('coordenadorias'))
  .then(() => queryInterface.bulkDelete('setores'))
  .then(() => queryInterface.bulkDelete('usuarios'))
  .then(() => queryInterface.bulkDelete('permissoes'))
};
